import os
def test1():
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  os.system("start cmd")
  print ("Started")
